// Su dung ham Math.abs()
let num1 = (-5.5)
let result1 = Math.abs(num1)
alert(result1)
let num2 = (10)
let result2 = Math.abs(num2)
alert(result2) 
// Su dung ham Math.ceil
let a = (4.4)
let result = Math.ceil(a)
alert(result)
let b = (5.8)
let result3 = Math.ceil(b)
alert(result3)
// Su dung ham Math.floor
let c = (5.7)
let result4 = Math.floor(c)
alert(result4)
let d = (6.1)
let result5 = Math.floor(d)
alert(result5)
// Su dung ham Math.round
let e = (10.1)
let result6 = Math.round(e)
alert(result6)
let f = (20.6)
let result7 = Math.round(f)
alert(result7)